import { Router } from "express";
import { validateRegisterUser, vlidateLoginUser } from "../validator/auth.validator.js";
import { register, login, googleAuthCallback } from "../controller/auth.controller.js";
import passport from "passport";

const authRouter = Router();

authRouter.post('/register', validateRegisterUser, register);
authRouter.post('/login', vlidateLoginUser, login)
//this route redirects user to google for authentication and token is generated by google and sent to the user and then to callback url
authRouter.get('/google', passport.authenticate('google', { scope: ['profile', 'email'] }))
//this route is the callback url that google redirects to after authentication and the token is sent to the google server for verfication and then google sends the user data to the app server and then the app server generates a token and sends it to the user
authRouter.get('/google/callback', passport.authenticate('google',
    {
        session: false,
        failureRedirect: process.env.NODE_ENV === 'production' ? '/login' : 'http://localhost:5173/login'
    })
    , googleAuthCallback)


export default authRouter;
